// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stereograph.TechnicalTest.Api.Models;

#nullable disable

namespace Stereograph.TechnicalTest.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230730200845_FollowingsTableCreation")]
    partial class FollowingsTableCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Stereograph.TechnicalTest.Api.Models.Following", b =>
                {
                    b.Property<int>("FollowedPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowedPersonId", "FollowerId");

                    b.HasIndex("FollowerId", "FollowedPersonId")
                        .IsUnique();

                    b.ToTable("Followings");
                });

            modelBuilder.Entity("Stereograph.TechnicalTest.Api.Models.Person", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Stereograph.TechnicalTest.Api.Models.Following", b =>
                {
                    b.HasOne("Stereograph.TechnicalTest.Api.Models.Person", "FollowedPerson")
                        .WithMany("FollowingsBy")
                        .HasForeignKey("FollowedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stereograph.TechnicalTest.Api.Models.Person", "Follower")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedPerson");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Stereograph.TechnicalTest.Api.Models.Person", b =>
                {
                    b.Navigation("Followings");

                    b.Navigation("FollowingsBy");
                });
#pragma warning restore 612, 618
        }
    }
}
